### PR TITLE
(PA-4125) Adds support for RHEL 9

### PR DESCRIPTION
**Pull request by mhashizume**

### CODE REVIEW

**Comment by mhashizume** [comment]
This was successfully tested at: https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-generic-builder-init_generic-builder/1305/

**Review by e-gris — APPROVED** [review]
Just want to confirm (because I'm not 100% certain) that we still need this for puppet6, correct?

**Comment by mhashizume** [comment]
> Just want to confirm (because I'm not 100% certain) that we still need this for puppet6, correct?

@e-gris I _think_ this PR should cover the puppet6 streams (from the changes in `puppet6-release.rb` and `puppet6-nightly-release.rb`).

If you're talking about testing the pipeline, I ran it against puppet6 here: https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-generic-builder-init_generic-builder/1306/

**Comment by e-gris** [comment]
I was just confirming that adding redhat 9 support to puppet 6 was _intentional_

I see from https://confluence.puppetlabs.com/display/PM/Puppet+Platform+6.26.0 that it was.

**Comment by mhashizume** [comment]
Ah yes, misunderstood what you were saying. Yes, RHEL9 support in puppet6 is intentional.

**Review by joshcooper — APPROVED** [review]

**Pull request merged**
