### PR TITLE
(RE-4196) Move puppetlabs-release to vanagon

### PR DESCRIPTION
**Pull request by haus**
This PR moves puppetlabs-release package building to a vanagon style
project. This allows us to remove the old bespoke 'automation' in favor
of something maintainable. The repo definitions are moved from erb
templates to a tokenized text file that is updated using sed in the
build. Platform configs were imported from the puppet-agent repository.

### CODE REVIEW

**Comment by haus** [comment]
Depends on https://github.com/puppetlabs/vanagon/pull/69 and https://github.com/puppetlabs/vanagon/pull/68

**Comment by shrug** [comment]
chuck-norris-thumbs-up

**Comment by melissa** [comment]
I don't know whether to be terrified or overjoyed...

**Comment by haus** [comment]
I've been going with joy so far.

**Pull request merged**
