### PR TITLE
(PA-1779) Add support for fedora-27-x86_64

### PR DESCRIPTION
**Pull request by mwaggett**
Platform config was copied from the fedora-26 one.

### CODE REVIEW

**Comment by underscorgan** [comment]
Does it build?

**Comment by mwaggett** [comment]
@underscorgan http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1430/

**Comment by underscorgan** [comment]
I've lost track of what the current state of affairs is, but will this have the correct incantation of fedora version (with/without the 'f' prefix)?

**Comment by mwaggett** [comment]
@underscorgan yes. The PC1 stream will always have the f. When I make these updates for puppet5, I'll have to do some rearranging when it comes time to ship because we updated this repo to not use the f because we though that was gonna be resolved way sooner (lol).

**Comment by mwaggett** [comment]
oh lol looks like https://github.com/puppetlabs/puppetlabs-release/pull/131 was already open, closing this.

**Pull request closed without merging**
