### PR TITLE
(maint) Clean ups, etc

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by stahnma** [comment]
do we want to keep the EOL platform definitions so that if/when we make an archives server, we can update the -release packages to point to that?

**Comment by melissa** [comment]
That's certainly not a bad idea. If you'd prefer we keep them around, I can definitely take that commit out

**Comment by melissa** [comment]
@stahnma I removed the commit that removed the EOL platforms

**Comment by shermdog** [comment]
:+1:

**Pull request merged**
