### PR TITLE
(RE-5373) Initial config for cisco-wrlinux-5-x86_64

### PR DESCRIPTION
**Pull request by shermdog**
This supports the re-naming of nxos to cisco-wrlinux

### CODE REVIEW

**Comment by ScottGarman** [comment]
:+1:

**Comment by haus** [comment]
I think the gemfile is going to need an update as well: https://github.com/shermdog/puppetlabs-release/blob/RE-5373/Gemfile#L3

**Comment by shermdog** [comment]
@haus I'm thinking that should be in a separate pull request - to support the switch of PC1 to the default branch.

**Comment by haus** [comment]
@shermdog okay, that PR needs to get merged first then. the is_cisco...? method won't exist in the vanagon specified currently.

**Pull request merged**
