### PR TITLE
Add Fedora 25 and Ubuntu 16.10 platforms

### PR DESCRIPTION
**Pull request by ScottGarman**
Add platform configs for release package generation on pl-build-tools.

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by stahnma** [comment]
I thought we weren't going to use pl-build-tools on these?

**Comment by ScottGarman** [comment]
@stahnma sorry, you weren't privy to these discussions I've had with Geoff on the topic. We're trying to get Fedora 25, Ubuntu 16.10, and Debian 9 into the 1.9.0 agent release. Since we don't know how much added work it's going to be to refactor things to work without pl-build-tools, I suggested a compromise: let's pick one of those three platforms to do that work on. Geoff and I agreed that Debian 9 would be the platform for doing this experiment on, and if it turns into a quagmire, we're okay with possibly missing Debian 9 in the 1.9.0 agent release. That's the reasoning here.

**Comment by ScottGarman** [comment]
Also, I think even if we use the build hosts' gcc, boost, and yaml-cpp, we still need something to package our custom cmake files.

**Comment by stahnma** [comment]
We would need a cmake file yes, but that's about it.

**Comment by stahnma** [comment]
FWIW, I already  have a branch for Ubuntu 16.04 that probably will get you a good portion of the way there for Debian 9.

**Pull request merged**
