### PR TITLE
(RE-12419) Create release package templates for apt.repos.puppet.com

### PR DESCRIPTION
**Pull request by e-gris**
Create release package templates for apt.repos.puppet.com

Separate supporting files by destination server into old-style (apt.puppetlabs.com, yum.puppetlabs.com, nightlies.puppet.com) and new (apt.repos.puppet.com)

Questions:

1. Any objections to the modified layout of the `files` directory?
2. The new package names, for example `puppet7-stable-apt-repos_7.0.0-1buster_all.deb` don't thrill me. I replaced `-release` with `-apt-repos` to distinguish. I'm struggling to think of something better. Any suggestions?

### CODE REVIEW

**Comment by e-gris** [comment]
testing is underway and looks good so far.

**Comment by e-gris** [comment]
I've tested and made a few small changes.

**Comment by GabrielNagy** [comment]
> 1. Any objections to the modified layout of the `files` directory?

Sounds good to me, the new layout makes things more clearer now.

> 2. The new package names, for example `puppet7-stable-apt-repos_7.0.0-1buster_all.deb` don't thrill me. I replaced `-release` with `-apt-repos` to distinguish. I'm struggling to think of something better. Any suggestions?

It feels a bit long indeed, but I can't come up with anything better. Will the `-release` packages be superseded by these at some point, or is the name that we're choosing final?

**Review by GabrielNagy — APPROVED** [review]
LGTM! Should there also be a rolling `puppet-stable-apt-repos` and `puppet-nightly-apt-repos`?

**Comment by e-gris** [comment]
Just checked in with Morgan:

- I'll make the rolling release packages that will essentially be duplicates of the puppet7. When puppet8 comes along, we'll move them to that.
- We'll try to get some product help with the package naming.

**Comment by e-gris** [comment]
> Will the `-release` packages be superseded by these at some point, or is the name that we're choosing final?

Hopefully, eventually. I expect we'll keep the old stuff around for puppet7 and release puppet8 here; I suspect we'll need a product management call to help decide.

I'm assuming we'll support both for quite a while.

**Pull request merged**
