### PR TITLE
(maint) Remove md5s from repo_definition config

### PR DESCRIPTION
**Pull request by mwaggett**
This commit removes the md5sums from the repo_definition. Since the files we
are installing here are local to this repo, rather than being pulled from
upstream, we don't really need to include the md5. This will also allow us to
move forward in our efforts to consolidate the branches of this repo, since
each repo file would have a different md5sum, which would be difficult and/or
ugly to include in a shared config.

### CODE REVIEW

**Comment by sarameisburger** [comment]
What was the reason for having it in the first place? Do we expect it to break anything if we remove it?

**Comment by mwaggett** [comment]
@sarameisburger I'm not sure why this was there in the first place. I'm *guessing* that when this was vanagonized, we used some other projects for reference and those projects (which install files from an external sources) had md5s recorded. but that's just a guess.

I talked to @shrug about this on Friday and he said he thinks it should be fine, but I'm gonna run a test build to be sure.

**Comment by underscorgan** [comment]
The initial vanagonization for the release packages happened before we removed the requirement for md5sums for local files (https://github.com/puppetlabs/vanagon/commit/bfb7f853e0ea21059187f6addb819ba249be8f07). This has been carried forward for new release packages but shouldn't be necessary.

**Comment by sarameisburger** [comment]
Sweet, sounds good to me

**Comment by mwaggett** [comment]
it builds! http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1714/

**Comment by e-gris** [comment]
[It builds!](https://media.giphy.com/media/c5eqVJN7oNLTq/giphy.gif)

**Pull request merged**
