### PR TITLE
(RE-11143) Merge puppet5-nightly -> master

### PR DESCRIPTION
**Pull request by mwaggett**
Merge conflicts were resolved by keeping all changes from puppet5-nightly.

### CODE REVIEW

**Comment by underscorgan** [comment]
@mwaggett is this basically just pushing puppet5-nightly-release to master?

**Comment by mwaggett** [comment]
@underscorgan yes. I plan to do each branch one-by-one, renaming things as-necessary, as I go.

**Comment by sarameisburger** [comment]
Can you point me towards the ticket/epic this is related to? This merge looks fine to me 👍 I think I'm just out of the loop on whats going on

**Comment by mwaggett** [comment]
whoops! @sarameisburger it's https://tickets.puppetlabs.com/browse/RE-11143

**Pull request merged**
