### PR TITLE
(PA-3219) Add support for fedora 32

### PR DESCRIPTION
**Pull request by sarameisburger**
only added to puppet6

### CODE REVIEW

**Comment by sarameisburger** [comment]
Can be reviewed but putting a do not merge until eric is done with his work and I confirm fedora 32 is only for puppet6

**Comment by sarameisburger** [comment]
Holding until PA is ready to ship fedora 32

**Comment by ciprianbadescu** [comment]
@sarameisburger, I think PA was already updated to ship Fedora 32

**Comment by sarameisburger** [comment]
@ciprianbadescu thank you for letting me know! I will get this rebased, merged, and built!

**Comment by ciprianbadescu** [comment]
@sarameisburger, can we add it also for puppet7?

**Pull request merged**
